### ISSUE TITLE
Replacing and selecting colour

### ISSUE THREAD

**Issue by varghult** [mirnovov/colourpicker#1]
Would it be possible to tweak the selection so I don't have to select the whole colour code before hitting cmd+*? To just hit cmd+* somewhere inside a color code would be magical.

PS! Thank you so much for this extension! As a tip, could you add 'color' as a keyword somewhere? I didn't find it at first since the search function in Nova wasn't fuzzy enough and I searched for 'color picker', not 'colour picker'.

**Comment by mirnovov** [comment]
Sorry for the late response @martin-pixelstore - this repo doesn't get that much activity so I don't check that often.

Unfortunately, I don't believe Nova has in-built functionality that allows me to do either - I actually thought about both during development, but came to the conclusion they couldn't be done.

I could do the first by looking for any instance of the appropriate characters and looking forwards/back from there, but that's a lot of work and could impair performance.

As for the latter, I could create another command that performs an identical operation, but with the American spelling, but that's a bit too unprofessional for my liking. You could DIY it though by downloading this repo, replacing "colour" with "color" via Cmd-F, and then building your own copy of the extension.

**Comment by mirnovov** [comment]
I'll close this issue for now - if anyone has an idea on how to fix either problem, I'll reopen.
